### ISSUE TITLE
Allow click on badge and jump to a url

### ISSUE THREAD

**Issue by linonetwo** [kookma/status-badge#1]
I hope the badge can be clicked, and jump to a tiddler or a webpage, so reader can get to know more info behind this badge.

BTW, can you make a nodejs version (folder-based) of this plugin? Thanks~

**Comment by kookma** [comment]
@linonetwo - this repo is rather old! Please see [Shiraz](https://github.com/kookma/TW-Shiraz) and look for status badge! 
In Shiraz there are different type of badge and clickable badges also can be found there!

A simple solution to make them clickable is like this: 

- Open Shiraz: https://kookma.github.io/TW-Shiraz/
- Create a new tiddler with below contents!

````
\define linkify-dbadge(subject, status, type:warning)
<style>.dbadge .dbadge-subject a {color:unset}</style>
<$macrocall $name=dbadge subject="""[[$subject$]]""" status=<<__status__>> type=<<__type__>> />
\end

<<linkify-dbadge "Shiraz Tutorial" 1.2.3>>
````

You will get

![img_538_chrome](https://user-images.githubusercontent.com/830394/135725464-37bebb41-cf17-4dcf-8ba1-cc587f97e3df.png)
